export const languageMap: Record<string, string> = {
    hindi: 'hi',
    english: 'en',
    spanish: 'es',
    french: 'fr',
    german: 'de',
    italian: 'it',
    portuguese: 'pt',
    japanese: 'ja',
    korean: 'ko',
    chinese: 'zh',
    dutch: 'nl',
    turkish: 'tr',
    russian: 'ru',
    arabic: 'ar',
}